// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// REGISTER
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// POST
export const GET_POST_START = "GET_POST_START";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

// single Post
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";

// USER
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// PROFILE
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
